### ISSUE TITLE
Variance calculation

### ISSUE THREAD

**Issue by karlbohlmark** [pgte/moving-average#2]
It looks like you missed dividing by the number of samples to get the actual variance. Currently the calculated variance is increasing indefinitely.

**Comment by dprime** [comment]
Yep can confirm.
https://github.com/pgte/moving-average/blob/master/index.js#L40 is the line in question.

**Comment by pgte** [comment]
@dprime any suggested fix?

**Comment by pgte** [comment]
Should be fixed in v0.1.0.
